version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  test:
    jobs:
      - node/test:
          # https://circleci.com/developer/images/image/cimg/node
          version: '17.4'
          pkg-manager: yarn
